### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [Azure/Azure-Maps-plugin-for-QGIS#7]
#Problem

Please fix links in 
![image](https://github.com/Azure/Azure-Maps-plugin-for-QGIS/assets/2510900/43b53bcb-7fe2-4386-a300-e33b96d5858d)

**Comment by tejitpabari99** [comment]
My bad, I thought it would take this from the updated metadata.txt
Updated now! The link for homepage: https://aka.ms/am-qgis-plugin will be updated as soon as the plugin goes live, with the latest documentation.
Thanks a lot.

**Comment by tejitpabari99** [comment]
@NyakudyaA Done!
